### ISSUE TITLE
Unable to build (react) project after upgrade to 1.1.0

### ISSUE THREAD

**Issue by systemmonkey42** [latysheff/node-polycrc#6]
After upgrading to polycrc 1.1.0, I can no longer build my react project.

running "npm run build" produces the following error;

```
Creating an optimized production build...
Failed to compile.

./node_modules/polycrc/polycrc.js
SyntaxError: /home/***project****/node_modules/polycrc/polycrc.js: Missing class properties transform.
  202 |   }
  203 |
> 204 |   fromByteArray = Buffer.from.bind(Buffer)
      |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  205 |   fromString = Buffer.from.bind(Buffer)
  206 | }
  207 |
```

Rolling back with `npm install polycrc@1.0.1` fixes the issue.

**Comment by mikaelsahlstrom** [comment]
I tested this with "Create React App" (react 17.0.2) and polycrc 1.1.1 and it works for me. Could this issue been resolved in one of the newer version of react?

**Comment by systemmonkey42** [comment]
Thanks for the reminder.

I can't upgrade to react@17 (or @18) without code changes, but I did a little digging and found a dependency used polycrc@1.0.1, and upgrading it to polycrc@1.1.0 (or 1.1.1) in the main react app caused the breakage.   Updating the dependency to use polycrc@1.1.1 fixed the issue.
